apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: pitstop
spec:
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP