apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/SalmaSAGH/pitstop_vehicle_kubernetes.git
    targetRevision: HEAD
    path: product-k8s
    repoURL: https://github.com/SalmaSAGH/vehicle-k8s.git
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: product-local

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
