apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
          ports:
            - containerPort: 5672 # Port pour la communication
            - containerPort: 15672 # Port pour l'interface de gestion
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: pitstop
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
