apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-container
          image: registry.gitlab.com/salmasagh/pitstop_vehicle/vehicle:0c210e04
          ports:
            - containerPort: 8082
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: "vehicle_db"
            - name: DB_HOST
              value: "vehicle-database"
            - name: DB_PORT
              value: "3306"
            - name: MESSAGE_BUS
              value: "rabbitmq"
            - name: MESSAGE_BUS_USERNAME
              value: "admin"
            - name: MESSAGE_BUS_PASSWORD
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: pitstop
spec:
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
  template:
    spec:
      containers:
        - image: registry.gitlab.com/salmasagh/pitstop_vehicle/vehicle:0c210e04
